base_urls:
  - http://localhost/ccr2
  - http://localhost/ccr2s

normalise:
  regexp:
    - ["/ccr2s/i", "ccr2"]
    - ["/\d{2}.+[a-z]{3,8}.+\d{4} \d{2}:\d{2}:\d{2}/i", "DATETIME"]

resources:
  - /
  - /datasheets
#  - /piecharts
#  - /123
#  - /configure
#  - xxx
#    - resource: configure
#    - _method: POST

